%Function Format
%[O_EnterpriseValueLow, O_EnterpriseValueHigh, ...
%          O_ProjectedRevenueSeries, O_ProjectedVariableCostSeries, O_ProjectedCashFlowSeries,...
%          O_PlotPeriod, O_ErrorCode]... 
%= RunValuation (I_Country, I_Industry, I_Debt, I_NonCashAssets, I_Cash,
%  I_YearlyFixedCost,
%  I_YearlyFinancialEntries[0].Revenue, I_YearlyFinancialEntries[0].CashFlow, 
%  I_YearlyFinancialEntries[1].Revenue, I_YearlyFinancialEntries[1].CashFlow, 
%  ...);

[O_EnterpriseValueLow, O_EnterpriseValueHigh, ...
          O_ProjectedRevenueSeries, O_ProjectedVariableCostSeries, O_ProjectedCashFlowSeries,...
          O_PlotPeriod, O_ErrorCode]... 
= RunValuation ("Egypt", "Advertising", 200000, 100000, 200000,
  100000,
  150000, 35000, 120000, 30000, 100000, 20000, 70000, 15000, 50000, 12000)
  